name: CI
on:
  push:
    branches: [ "dev", "release/*" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: For Dev branch
        run: echo Hello, world!

  For-release:
    if: contains(github.ref, release)
#     steps:
#     - run: echo "I only run if the branch has release in its name!"
#     if: contains(github.ref_name, "release")
    runs-on: ubuntu-latest
    steps:
      - name: For Release branch
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
     
      #
    
      
